# Generated by Django 3.2.4 on 2022-03-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('creation_time', models.DateTimeField(auto_now_add=True, db_column='TimeCreated')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('activated_time', models.DateTimeField(blank=True, db_column='TimeActivated', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_time', models.DateTimeField(blank=True, db_column='TimeDeleted', null=True)),
                ('idAdmin', models.AutoField(db_column='IdAdmin', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='FirstName', max_length=50)),
                ('lastName', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('phone', models.CharField(db_column='Phone', max_length=50)),
                ('is_suspended', models.BooleanField(db_column='IsSuspended', default=False)),
                ('suspended_time', models.DateTimeField(blank=True, db_column='TimeSuspended', null=True)),
                ('suspended_reason', models.CharField(blank=True, db_column='SuspendedReason', max_length=100, null=True)),
                ('lastSeen', models.DateTimeField(blank=True, db_column='LastSeen', null=True)),
                ('lastActivity', models.TextField(db_column='LastActivity')),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('creation_time', models.DateTimeField(auto_now_add=True, db_column='TimeCreated')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('activated_time', models.DateTimeField(blank=True, db_column='TimeActivated', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_time', models.DateTimeField(blank=True, db_column='TimeDeleted', null=True)),
                ('idDepartment', models.AutoField(db_column='IdDepartment', primary_key=True, serialize=False)),
                ('departmentNameAr', models.CharField(db_column='DepartmentNameAr', max_length=255)),
                ('departmentNameEn', models.CharField(db_column='DepartmentNameEn', max_length=255)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('creation_time', models.DateTimeField(auto_now_add=True, db_column='TimeCreated')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('activated_time', models.DateTimeField(blank=True, db_column='TimeActivated', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_time', models.DateTimeField(blank=True, db_column='TimeDeleted', null=True)),
                ('idEmployee', models.AutoField(db_column='IdEmployee', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='FirstName', max_length=50)),
                ('lastName', models.CharField(db_column='LastName', max_length=50)),
                ('nationalId', models.CharField(db_column='NationalId', max_length=14)),
                ('phone', models.CharField(db_column='Phone', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('address', models.CharField(default='{Rubusta}', max_length=50)),
                ('baseSalary', models.FloatField(db_column='BaseSalary', max_length=50)),
                ('department', models.ForeignKey(db_column='IdDepartment', on_delete=django.db.models.deletion.CASCADE, to='Salary.department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='SalaryLog',
            fields=[
                ('creation_time', models.DateTimeField(auto_now_add=True, db_column='TimeCreated')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('activated_time', models.DateTimeField(blank=True, db_column='TimeActivated', null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_time', models.DateTimeField(blank=True, db_column='TimeDeleted', null=True)),
                ('idSalaryLog', models.AutoField(db_column='idSalaryLog', primary_key=True, serialize=False)),
                ('previousBaseSalary', models.FloatField(db_column='PreviousBaseSalary', max_length=50)),
                ('BaseSalary', models.FloatField(db_column='BaseSalary', max_length=50)),
                ('employee', models.ForeignKey(db_column='IdEmployee', on_delete=django.db.models.deletion.CASCADE, to='Salary.employee')),
            ],
            options={
                'db_table': 'SalaryLog',
            },
        ),
    ]
